#这是spring cloud config 全局配置，所有的的用户都能看得到
info:
  description: Spring Cloud Config ，All Client Can See And Use
  url: https://github.com/keryhu/cloud-config



      
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  password: password
  instance:
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
       defaultZone: http://${domain.name:localhost}:8761/eureka/


