#这是spring cloud config 全局配置，所有的的用户都能看得到
info:
  description: Spring Cloud Config ，All Client Can See And Use
  url: https://github.com/keryhu/cloud-config



      
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  password: '{cipher}AQBtzK5N6P43YVBOSSX9TT7+V3U9F51hUihSTAhPn0jZS+BwhsaIH99r1CotzHmLQUhWqnq8UvhnFuIKmOFfDjzJUEkPC8+ZtETj3iGglJWKZuGYzVNaF53lbsaObiTNc90U/9vcbheQ/bEk9XCg4sBZ7Y4g7D3UI86542MLaLuZU3ca1h3P+WHcT8XriXQ2s2/CY7Hh4hWMMLfYpPs3zzVNOjB7Tc8tQ9MI728bsNg4oSxrfxY+uRJsiO9weYlgDBhnIB3ht7XbtLvLS1wrXwPH2HR0lS9X+ncutkzjNeFGWvDnqYh3wUbuabwNxxDZEvZTfL4MupKEWxhdT4KCPmM9DLoqptCLYEdkNV89yoaQ/m3xF+NzZDWPedX/30y/m8Y='
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
       defaultZone: http://15900455491:${eureka.password}@${domain.name:localhost}:8761/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApVuOPKLwgnZxosn1zUH35nHq0bTxbcky8y9VgYg+1/XAWj6hPftDyUIXcH2vaRauoJxCf6QtpID3kcQCGVFvzkrQrNT1+2y+OjqKMmgZPe6EF6qd+1djqgfSzOSQuyIrFfhmMO84KMhyuL6wZnq0fqgqIZIXmzzyd5j12JL3jIHxsv8m5b7Crk+XuQToKCId1rTXB17t+ZmNjc6TXkmdcsCqiBRbKZ7N//VH33nNIxbFHF1uFEDrdLI2ziG/iGt9cS9dVvecgLgmPaE45ALgbv8WQycEMjCD/jopfhb2u+ybcOAEoH1pzjX4WHEVoGjVadyBE8hq9U4aH1x+Cji0kwIDAQAB
          -----END PUBLIC KEY----- 


spring:
 cloud:
   inetutils:
     ignoredInterfaces:
       - docker0
       - veth.*

#取得当前的ip地址
hostProperty:
  hostName: http://${domain.name:localhost}
  
