#这是spring cloud config 全局配置，所有的的用户都能看得到
info:
  description: Spring Cloud Config ，All Client Can See And Use
  url: https://github.com/keryhu/cloud-config



      
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
       defaultZone: http://15900455491:skdjf7782c@${domain.name:localhost}:8761/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

security:
  oauth2:
    resource:
      user-info-uri: http://${domain.name:localhost}:9999/uaa/user


spring:
 cloud:
   inetutils:
     ignoredInterfaces:
       - docker0
       - veth.*

#取得当前的ip地址
hostProperty:
  hostName: http://${domain.name:localhost}