#这是spring cloud config 全局配置，所有的的用户都能看得到
info:
  description: Spring Cloud Config ，All Client Can See And Use
  url: https://github.com/keryhu/cloud-config
  
spring:
  #profiles: docker
  cloud:
    config:
      uri: http://user:password@${CONFIGSERVER_PORT_8888_TCP_ADDR:localhost}:8888
      
      
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://user:password@${EUREKA_PORT_8761_TCP_ADDR:localhost}:8761/eureka/


