#这是spring cloud config 全局配置，所有的的用户都能看得到
info:
  description: Spring Cloud Config ，All Client Can See And Use
  url: https://github.com/keryhu/cloud-config



      
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  password: password
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_PORT_8761_TCP_ADDR:localhost}:8761/eureka/


