info:
  auth-server: this is auth-server config yml
  
spring:
  data:
    mongodb:
      uri: mongodb://test:123456@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/test
      repositories:
        enabled: true
  
