

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
